spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: XPLABS
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    username: sys as sysdba
    password: oracle
