plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
}

// The plugins the convention plugins in src/main/groovy apply, by their plugin marker coordinates.
dependencies {
    implementation 'com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin:0.37.0'
    implementation 'me.champeau.gradle.japicmp:me.champeau.gradle.japicmp.gradle.plugin:0.4.6'
    implementation 'org.gradlex.extra-java-module-info:org.gradlex.extra-java-module-info.gradle.plugin:1.14.2'
}
