name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Configure GPG Settings for Signing
      id: gpg
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      run: |
        export GPG_TTY=$(tty)
        echo "$GPG_KEY" > key.asc
        gpg --batch --import key.asc
        gpg --keyserver keyserver.ubuntu.com --send-keys "$GPG_KEY_ID"
        gpg --export-secret-key "$GPG_KEY_ID" > secring.gpg
    - name: Build & Deploy
      id: deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      run: ./gradlew clean build publishToSonatype closeAndReleaseSonatypeStagingRepository -Psigning.keyId="${GPG_KEY_ID}" -Psigning.password="${GPG_PASSWORD}" -Psigning.secretKeyRingFile="./secring.gpg"
